version: "3"

services:
  pgsql:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    container_name: "pg_biblioteca"
    restart: always
    environment:
      POSTGRES_USER: ${DB_PG_USERNAME}
      POSTGRES_PASSWORD: ${DB_PG_PASSWORD}
      POSTGRES_DB: ${DB_PG_DATABASE}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
